name 'puppetlabs-nginx'
version '0.1.0'

author 'puppetlabs'
license 'Apache License Version 2.0'
project_page 'http://github.com/puppetlabs/puppetlabs-nginx'
source 'http://github.com/puppetlabs/puppetlabs-nginx'
summary 'Puppet NGINX management module'
description 'This module can be used for basic NGINX Management'
dependency 'puppetlabs/stdlib', '>=0.1.6'
